{% set name = "airflow-supervisor" %}
{% set version = "1.8.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/airflow-supervisor/airflow_supervisor-{{ version }}.tar.gz
  sha256: 32eb5863cf611676025bf4018dc85ce6e5227cefe77dcee4a767514b37ba5c40

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - airflow-common-operators >=0.6,<0.7
    - airflow-ha
    - airflow-pydantic >=1.2.8,<1.4
    - apache-airflow >=2.8,<3
    - supervisor-pydantic >=1.3,<1.4

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - airflow_supervisor

about:
  home: https://github.com/airflow-laminar/airflow-supervisor
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Supervisor operators and configuration for long-running tasks
  description: Supervisor operators and configuration for long-running tasks
  dev_url: https://github.com/airflow-laminar/airflow-supervisor

extra:
  recipe-maintainers:
    - timkpaine
