{% set name = "airflow-supervisor" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/airflow-supervisor/airflow_supervisor-{{ version }}.tar.gz
  sha256: afe183f63d48a81552fd15e478f237432e7c0e2c74a9488b903696bf11c5ec30

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - airflow-ha
    - apache-airflow >=2,<3
    - colorlog
    - hydra-core
    - jinja2
    - omegaconf
    - pydantic >=2
    - rich
    - typer
  run_constrained:
    - airflow-config >=0.1.2

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - airflow_supervisor

about:
  home: https://github.com/airflow-laminar/airflow-supervisor
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Supervisor operators and configuration for long-running tasks
  description: Supervisor operators and configuration for long-running tasks
  dev_url: https://github.com/airflow-laminar/airflow-supervisor

extra:
  recipe-maintainers:
    - timkpaine
