{% set name = "airflow-supervisor" %}
{% set version = "1.10.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/airflow-supervisor/airflow_supervisor-{{ version }}.tar.gz
  sha256: 5d0ef6c54fe1d393e1a3e884288032768f15984a4cba0b000520f2048db57848

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - airflow-ha >=1.4.1,<1.7
    - airflow-pydantic >=1.5.4,<1.6
    - supervisor-pydantic >=1.3,<1.4

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - airflow_supervisor

about:
  home: https://github.com/airflow-laminar/airflow-supervisor
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Supervisor operators and configuration for long-running tasks
  description: Supervisor operators and configuration for long-running tasks
  dev_url: https://github.com/airflow-laminar/airflow-supervisor

extra:
  recipe-maintainers:
    - timkpaine
