{% set name = "airflow-supervisor" %}
{% set version = "1.7.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/airflow-supervisor/airflow_supervisor-{{ version }}.tar.gz
  sha256: 7933f46d4ff3d8859bd774c13a903bd66e83029de55b384a0c8ca68c6b439bd6

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - airflow-common-operators >=0.5,<0.6
    - airflow-ha >=1.4,<1.5
    - apache-airflow >=2.8,<3
    - supervisor-pydantic >=1.2.4,<1.3

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - airflow_supervisor

about:
  home: https://github.com/airflow-laminar/airflow-supervisor
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Supervisor operators and configuration for long-running tasks
  description: Supervisor operators and configuration for long-running tasks
  dev_url: https://github.com/airflow-laminar/airflow-supervisor

extra:
  recipe-maintainers:
    - timkpaine
